 name: Android CI
 
 on:
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 17 for SDK tools
         id: jdk17
         uses: actions/setup-java@v3
         with:
           distribution: 'temurin'
           java-version: '17'
       - name: Set up Android SDK
         uses: android-actions/setup-android@v3
         with:
           packages: 'build-tools;34.0.0 platforms;android-34 platform-tools'
           log-accepted-android-sdk-licenses: false
       - name: Set up JDK 8 for build
         id: jdk8
         uses: actions/setup-java@v3
         with:
           distribution: 'temurin'
           java-version: '8'
       - name: Build Debug
         run: |
           cd Application
           ./gradlew assembleDebug
