name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        id: jdk17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'build-tools;34.0.0 platforms;android-34 platform-tools'
          log-accepted-android-sdk-licenses: false
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Node dependencies
        run: npm install
      - name: Prepare project files
        run: |
          cp Application/LinkBubble/src/main/AndroidManifest.xml.template Application/LinkBubble/src/main/AndroidManifest.xml
          cp Application/LinkBubble/src/main/java/com/linkbubble/ConfigAPIs.java.template Application/LinkBubble/src/main/java/com/linkbubble/ConfigAPIs.java
          echo "sdk.dir=$ANDROID_HOME" > Application/local.properties
      - name: Build Debug
        run: |
          cd Application
          ./gradlew assembleDebug
